const fs = require('fs');
const path = require('path');

const cities = [
  { city: 'Mumbai', state: 'Maharashtra' },
  { city: 'Delhi', state: 'Delhi' },
  { city: 'Bengaluru', state: 'Karnataka' },
  { city: 'Hyderabad', state: 'Telangana' },
  { city: 'Ahmedabad', state: 'Gujarat' },
  { city: 'Chennai', state: 'Tamil Nadu' },
  { city: 'Kolkata', state: 'West Bengal' },
  { city: 'Surat', state: 'Gujarat' },
  { city: 'Pune', state: 'Maharashtra' },
  { city: 'Jaipur', state: 'Rajasthan' },
  { city: 'Lucknow', state: 'Uttar Pradesh' },
  { city: 'Kanpur', state: 'Uttar Pradesh' },
  { city: 'Nagpur', state: 'Maharashtra' },
  { city: 'Indore', state: 'Madhya Pradesh' },
  { city: 'Thane', state: 'Maharashtra' },
  { city: 'Bhopal', state: 'Madhya Pradesh' },
  { city: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { city: 'Pimpri-Chinchwad', state: 'Maharashtra' },
  { city: 'Patna', state: 'Bihar' },
  { city: 'Vadodara', state: 'Gujarat' },
  { city: 'Ghaziabad', state: 'Uttar Pradesh' },
  { city: 'Ludhiana', state: 'Punjab' },
  { city: 'Agra', state: 'Uttar Pradesh' },
  { city: 'Nashik', state: 'Maharashtra' },
  { city: 'Faridabad', state: 'Haryana' },
  { city: 'Meerut', state: 'Uttar Pradesh' },
  { city: 'Rajkot', state: 'Gujarat' },
  { city: 'Kalyan-Dombivli', state: 'Maharashtra' },
  { city: 'Vasai-Virar', state: 'Maharashtra' },
  { city: 'Varanasi', state: 'Uttar Pradesh' },
  { city: 'Srinagar', state: 'Jammu and Kashmir' },
  { city: 'Aurangabad', state: 'Maharashtra' },
  { city: 'Dhanbad', state: 'Jharkhand' },
  { city: 'Amritsar', state: 'Punjab' },
  { city: 'Navi Mumbai', state: 'Maharashtra' },
  { city: 'Prayagraj', state: 'Uttar Pradesh' },
  { city: 'Howrah', state: 'West Bengal' },
  { city: 'Ranchi', state: 'Jharkhand' },
  { city: 'Jabalpur', state: 'Madhya Pradesh' },
  { city: 'Gwalior', state: 'Madhya Pradesh' },
  { city: 'Guwahati', state: 'Assam' },
  { city: 'Chandigarh', state: 'Chandigarh' },
  { city: 'Solapur', state: 'Maharashtra' },
  { city: 'Hubli–Dharwad', state: 'Karnataka' },
  { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { city: 'Tiruppur', state: 'Tamil Nadu' },
  { city: 'Moradabad', state: 'Uttar Pradesh' },
  { city: 'Mysore', state: 'Karnataka' },
  { city: 'Bareilly', state: 'Uttar Pradesh' },
  { city: 'Gurgaon', state: 'Haryana' },
  { city: 'Aligarh', state: 'Uttar Pradesh' },
  { city: 'Jalandhar', state: 'Punjab' },
  { city: 'Bhubaneswar', state: 'Odisha' },
  { city: 'Salem', state: 'Tamil Nadu' },
  { city: 'Mira-Bhayandar', state: 'Maharashtra' },
  { city: 'Warangal', state: 'Telangana' },
  { city: 'Thiruvananthapuram', state: 'Kerala' },
  { city: 'Guntur', state: 'Andhra Pradesh' },
  { city: 'Bhiwandi', state: 'Maharashtra' },
  { city: 'Saharanpur', state: 'Uttar Pradesh' },
  { city: 'Gorakhpur', state: 'Uttar Pradesh' },
  { city: 'Bikaner', state: 'Rajasthan' },
  { city: 'Amravati', state: 'Maharashtra' },
  { city: 'Noida', state: 'Uttar Pradesh' },
  { city: 'Jamshedpur', state: 'Jharkhand' },
  { city: 'Bhilai', state: 'Chhattisgarh' },
  { city: 'Cuttack', state: 'Odisha' },
  { city: 'Firozabad', state: 'Uttar Pradesh' },
  { city: 'Kochi', state: 'Kerala' },
  { city: 'Nellore', state: 'Andhra Pradesh' },
  { city: 'Bhavnagar', state: 'Gujarat' },
  { city: 'Dehradun', state: 'Uttarakhand' },
  { city: 'Durgapur', state: 'West Bengal' },
  { city: 'Asansol', state: 'West Bengal' },
  { city: 'Nanded', state: 'Maharashtra' },
  { city: 'Kolhapur', state: 'Maharashtra' },
  { city: 'Ajmer', state: 'Rajasthan' },
  { city: 'Gulbarga', state: 'Karnataka' },
  { city: 'Jamnagar', state: 'Gujarat' },
  { city: 'Ujjain', state: 'Madhya Pradesh' },
  { city: 'Loni', state: 'Uttar Pradesh' },
  { city: 'Siliguri', state: 'West Bengal' },
  { city: 'Jhansi', state: 'Uttar Pradesh' },
  { city: 'Ulhasnagar', state: 'Maharashtra' },
  { city: 'Jammu', state: 'Jammu and Kashmir' },
  { city: 'Sangli-Miraj & Kupwad', state: 'Maharashtra' },
  { city: 'Mangalore', state: 'Karnataka' },
  { city: 'Erode', state: 'Tamil Nadu' },
  { city: 'Belgaum', state: 'Karnataka' },
  { city: 'Ambattur', state: 'Tamil Nadu' },
  { city: 'Tirunelveli', state: 'Tamil Nadu' },
  { city: 'Malegaon', state: 'Maharashtra' },
  { city: 'Gaya', state: 'Bihar' },
  { city: 'Jalgaon', state: 'Maharashtra' },
  { city: 'Udaipur', state: 'Rajasthan' },
  { city: 'Maheshtala', state: 'West Bengal' },
  { city: 'Davanagere', state: 'Karnataka' },
  { city: 'Kozhikode', state: 'Kerala' },
  { city: 'Kurnool', state: 'Andhra Pradesh' },
  { city: 'Akola', state: 'Maharashtra' },
  { city: 'Rajpur Sonarpur', state: 'West Bengal' },
  { city: 'Rajahmundry', state: 'Andhra Pradesh' },
  { city: 'Bokaro', state: 'Jharkhand' },
  { city: 'South Dumdum', state: 'West Bengal' },
  { city: 'Bellary', state: 'Karnataka' },
  { city: 'Patiala', state: 'Punjab' },
  { city: 'Gopalpur', state: 'West Bengal' },
  { city: 'Agartala', state: 'Tripura' },
  { city: 'Bhagalpur', state: 'Bihar' },
  { city: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { city: 'Bhatpara', state: 'West Bengal' },
  { city: 'Panihati', state: 'West Bengal' },
  { city: 'Latur', state: 'Maharashtra' },
  { city: 'Dhule', state: 'Maharashtra' },
  { city: 'Tirupati', state: 'Andhra Pradesh' },
  { city: 'Rohtak', state: 'Haryana' },
  { city: 'Korba', state: 'Chhattisgarh' },
  { city: 'Bhilwara', state: 'Rajasthan' },
  { city: 'Berhampur', state: 'Odisha' },
  { city: 'Muzaffarpur', state: 'Bihar' },
  { city: 'Ahmednagar', state: 'Maharashtra' },
  { city: 'Mathura', state: 'Uttar Pradesh' },
  { city: 'Kollam', state: 'Kerala' },
  { city: 'Avadi', state: 'Tamil Nadu' },
  { city: 'Kadapa', state: 'Andhra Pradesh' },
  { city: 'Kamarhati', state: 'West Bengal' },
  { city: 'Bilaspur', state: 'Chhattisgarh' },
  { city: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { city: 'Bijapur', state: 'Karnataka' },
  { city: 'Rampur', state: 'Uttar Pradesh' },
  { city: 'Shivamogga', state: 'Karnataka' },
  { city: 'Chandrapur', state: 'Maharashtra' },
  { city: 'Junagadh', state: 'Gujarat' },
  { city: 'Thrissur', state: 'Kerala' },
  { city: 'Alwar', state: 'Rajasthan' },
  { city: 'Bardhaman', state: 'West Bengal' },
  { city: 'Kulti', state: 'West Bengal' },
  { city: 'Kakinada', state: 'Andhra Pradesh' },
  { city: 'Nizamabad', state: 'Telangana' },
  { city: 'Parbhani', state: 'Maharashtra' },
  { city: 'Tumkur', state: 'Karnataka' },
  { city: 'Khammam', state: 'Telangana' },
  { city: 'Ozhukarai', state: 'Puducherry' },
  { city: 'Bihar Sharif', state: 'Bihar' },
  { city: 'Panipat', state: 'Haryana' },
  { city: 'Darbhanga', state: 'Bihar' },
  { city: 'Bally', state: 'West Bengal' },
  { city: 'Aizawl', state: 'Mizoram' },
  { city: 'Dewas', state: 'Madhya Pradesh' },
  { city: 'Ichalkaranji', state: 'Maharashtra' },
  { city: 'Karnal', state: 'Haryana' },
  { city: 'Bathinda', state: 'Punjab' },
  { city: 'Jalna', state: 'Maharashtra' },
  { city: 'Eluru', state: 'Andhra Pradesh' },
  { city: 'Kirari Suleman Nagar', state: 'Delhi' },
  { city: 'Barasat', state: 'West Bengal' },
  { city: 'Purnia', state: 'Bihar' },
  { city: 'Satna', state: 'Madhya Pradesh' },
  { city: 'Mau', state: 'Uttar Pradesh' },
  { city: 'Sonipat', state: 'Haryana' },
  { city: 'Farrukhabad', state: 'Uttar Pradesh' },
  { city: 'Sagar', state: 'Madhya Pradesh' },
  { city: 'Rourkela', state: 'Odisha' },
  { city: 'Durg', state: 'Chhattisgarh' },
  { city: 'Imphal', state: 'Manipur' },
  { city: 'Ratlam', state: 'Madhya Pradesh' },
  { city: 'Hapur', state: 'Uttar Pradesh' },
  { city: 'Arrah', state: 'Bihar' },
  { city: 'Karimnagar', state: 'Telangana' },
  { city: 'Anantapur', state: 'Andhra Pradesh' },
  { city: 'Etawah', state: 'Uttar Pradesh' },
  { city: 'Ambarnath', state: 'Maharashtra' },
  { city: 'North Dumdum', state: 'West Bengal' },
  { city: 'Bharatpur', state: 'Rajasthan' },
  { city: 'Begusarai', state: 'Bihar' },
  { city: 'New Delhi', state: 'Delhi' },
  { city: 'Gandhidham', state: 'Gujarat' },
  { city: 'Baranagar', state: 'West Bengal' },
  { city: 'Tiruvottiyur', state: 'Tamil Nadu' },
  { city: 'Puducherry', state: 'Puducherry' },
  { city: 'Sikar', state: 'Rajasthan' },
  { city: 'Thoothukudi', state: 'Tamil Nadu' },
  { city: 'Rewa', state: 'Madhya Pradesh' },
  { city: 'Mirzapur', state: 'Uttar Pradesh' },
  { city: 'Raichur', state: 'Karnataka' },
  { city: 'Pali', state: 'Rajasthan' },
  { city: 'Ramagundam', state: 'Telangana' },
  { city: 'Haridwar', state: 'Uttarakhand' },
  { city: 'Vijayanagaram', state: 'Andhra Pradesh' },
  { city: 'Katihar', state: 'Bihar' },
  { city: 'Nagercoil', state: 'Tamil Nadu' },
  { city: 'Sri Ganganagar', state: 'Rajasthan' },
  { city: 'Karawal Nagar', state: 'Delhi' },
  { city: 'Mango', state: 'Jharkhand' },
  { city: 'Thanjavur', state: 'Tamil Nadu' },
  { city: 'Bulandshahr', state: 'Uttar Pradesh' },
  { city: 'Uluberia', state: 'West Bengal' },
  { city: 'Murwara', state: 'Uttar Pradesh' },
  { city: 'Sambhal', state: 'Uttar Pradesh' },
  { city: 'Singrauli', state: 'Madhya Pradesh' },
  { city: 'Nadiad', state: 'Gujarat' },
  { city: 'Secunderabad', state: 'Telangana' },
  { city: 'Naihati', state: 'West Bengal' },
  { city: 'Yamunanagar', state: 'Haryana' },
  { city: 'Bidhan Nagar', state: 'West Bengal' },
  { city: 'Pallavaram', state: 'Tamil Nadu' },
  { city: 'Bidar', state: 'Karnataka' },
  { city: 'Munger', state: 'Bihar' },
  { city: 'Panchkula', state: 'Haryana' },
  { city: 'Burhanpur', state: 'Madhya Pradesh' },
  { city: 'Raurkela Industrial Township', state: 'Odisha' },
  { city: 'Kharagpur', state: 'West Bengal' },
  { city: 'Dindigul', state: 'Tamil Nadu' },
  { city: 'Gandhinagar', state: 'Gujarat' },
  { city: 'Hospet', state: 'Karnataka' },
  { city: 'Nangloi Jat', state: 'Delhi' },
  { city: 'Malda', state: 'West Bengal' },
  { city: 'Ongole', state: 'Andhra Pradesh' },
  { city: 'Deoghar', state: 'Jharkhand' },
  { city: 'Chapra', state: 'Bihar' },
  { city: 'Haldia', state: 'West Bengal' },
  { city: 'Khandwa', state: 'Madhya Pradesh' },
  { city: 'Nandyal', state: 'Andhra Pradesh' },
  { city: 'Chittoor', state: 'Andhra Pradesh' },
  { city: 'Morena', state: 'Madhya Pradesh' },
  { city: 'Amroha', state: 'Uttar Pradesh' },
  { city: 'Anand', state: 'Gujarat' },
  { city: 'Bhind', state: 'Madhya Pradesh' },
  { city: 'Bhalswa Jahangir Pur', state: 'Delhi' },
  { city: 'Madhyamgram', state: 'West Bengal' },
  { city: 'Bhiwani', state: 'Haryana' },
  { city: 'Baharampur', state: 'West Bengal' },
  { city: 'Ambala', state: 'Haryana' },
  { city: 'Morvi', state: 'Gujarat' },
  { city: 'Fatehpur', state: 'Uttar Pradesh' },
  { city: 'Rae Bareli', state: 'Uttar Pradesh' },
  { city: 'Khora', state: 'Uttar Pradesh' },
  { city: 'Bhusawal', state: 'Maharashtra' },
  { city: 'Orai', state: 'Uttar Pradesh' },
  { city: 'Bahraich', state: 'Uttar Pradesh' },
  { city: 'Vellore', state: 'Tamil Nadu' },
  { city: 'Mahesana', state: 'Gujarat' },
  { city: 'Sambalpur', state: 'Odisha' },
  { city: 'Raiganj', state: 'West Bengal' },
  { city: 'Sirsa', state: 'Haryana' },
  { city: 'Danapur', state: 'Bihar' },
  { city: 'Serampore', state: 'West Bengal' },
  { city: 'Sultan Pur Majra', state: 'Delhi' },
  { city: 'Guna', state: 'Madhya Pradesh' },
  { city: 'Jaunpur', state: 'Uttar Pradesh' },
  { city: 'Panvel', state: 'Maharashtra' },
  { city: 'Shivpuri', state: 'Madhya Pradesh' },
  { city: 'Surendranagar Dudhrej', state: 'Gujarat' },
  { city: 'Unnao', state: 'Uttar Pradesh' },
  { city: 'Hugli-Chuchura', state: 'West Bengal' },
  { city: 'Badlapur', state: 'Maharashtra' },
  { city: 'Alappuzha', state: 'Kerala' },
  { city: 'Kottayam', state: 'Kerala' },
  { city: 'Gadag-Betageri', state: 'Karnataka' },
  { city: 'Machilipatnam', state: 'Andhra Pradesh' },
  { city: 'Shimla', state: 'Himachal Pradesh' },
  { city: 'Adoni', state: 'Andhra Pradesh' },
  { city: 'Tenali', state: 'Andhra Pradesh' },
  { city: 'Proddatur', state: 'Andhra Pradesh' },
  { city: 'Saharsa', state: 'Bihar' },
  { city: 'Hindupur', state: 'Andhra Pradesh' },
  { city: 'Sasaram', state: 'Bihar' },
  { city: 'Hajipur', state: 'Bihar' },
  { city: 'Beed', state: 'Maharashtra' },
  { city: 'Bhimavaram', state: 'Andhra Pradesh' },
  { city: 'Dehri', state: 'Bihar' },
  { city: 'Madanapalle', state: 'Andhra Pradesh' },
  { city: 'Siwan', state: 'Bihar' },
  { city: 'Bettiah', state: 'Bihar' },
  { city: 'Gondia', state: 'Maharashtra' },
  { city: 'Guntakal', state: 'Andhra Pradesh' },
  { city: 'Srikakulam', state: 'Andhra Pradesh' },
  { city: 'Motihari', state: 'Bihar' },
  { city: 'Dharmavaram', state: 'Andhra Pradesh' },
  { city: 'Satara', state: 'Maharashtra' },
  { city: 'Barshi', state: 'Maharashtra' },
  { city: 'Gudivada', state: 'Andhra Pradesh' },
  { city: 'Yavatmal', state: 'Maharashtra' },
  { city: 'Narasaraopet', state: 'Andhra Pradesh' },
  { city: 'Bagaha', state: 'Bihar' },
  { city: 'Achalpur', state: 'Maharashtra' },
  { city: 'Osmanabad', state: 'Maharashtra' },
  { city: 'Nandurbar', state: 'Maharashtra' },
  { city: 'Miryalaguda', state: 'Telangana' },
  { city: 'Tadipatri', state: 'Andhra Pradesh' },
  { city: 'Kishanganj', state: 'Bihar' },
  { city: 'Wardha', state: 'Maharashtra' },
  { city: 'Karaikudi', state: 'Tamil Nadu' },
  { city: 'Suryapet', state: 'Telangana' },
  { city: 'Jamalpur', state: 'Bihar' },
  { city: 'Kavali', state: 'Andhra Pradesh' },
  { city: 'Tadepalligudem', state: 'Andhra Pradesh' },
  { city: 'Udgir', state: 'Maharashtra' },
  { city: 'Amaravati', state: 'Andhra Pradesh' },
  { city: 'Buxar', state: 'Bihar' },
  { city: 'Jehanabad', state: 'Bihar' },
  { city: 'Hinganghat', state: 'Maharashtra' },
  { city: 'Aurangabad', state: 'Bihar' },
];

const names = [
  'Aarav', 'Vihaan', 'Vivaan', 'Ananya', 'Diya', 'Ishaan', 'Ayaan',
  'Rohan', 'Priya', 'Rahul', 'Aditi', 'Arjun', 'Saanvi', 'Vikram',
  'Sneha', 'Krishna', 'Anika', 'Kabir', 'Myra', 'Advik', 'Aadhya',
  'Arnav', 'Anvi', 'Dhruv', 'Kiara', 'Reyansh', 'Siya', 'Aarush',
  'Navya', 'Rudra', 'Angel', 'Om', 'Pari', 'Sai', 'Gauri', 'Shaurya',
  'Ira', 'Veer', 'Avni', 'Atharv', 'Kavya', 'Daksh', 'Sia', 'Ritvik',
  'Riya', 'Zain', 'Shanaya', 'Yash', 'Aisha', 'Dev', 'Tara',
];

const skills = {
  'Plumber': ['Pipe Installation', 'Drain Cleaning', 'Leak Repair'],
  'Electrician': ['Wiring', 'Fixture Installation', 'Panel Upgrades'],
  'Carpenter': ['Furniture Making', 'Framing', 'Finish Carpentry'],
  'Painter': ['Interior Painting', 'Exterior Painting', 'Faux Finishes'],
  'AC Technician': ['Installation', 'Repair', 'Maintenance'],
  'Appliance Repair': ['Refrigerator Repair', 'Washing Machine Repair'],
  'Mobile Repair': ['Screen Replacement', 'Battery Replacement', 'Water Damage'],
  'Laptop Repair': ['Hardware Repair', 'Software Troubleshooting', 'Data Recovery'],
  'Car Mechanic': ['Engine Repair', 'Brake Services', 'Oil Change'],
  'Bike Mechanic': ['Tire Repair', 'Engine Tuning', 'Chain Maintenance'],
};

const getRandomItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const generateTechnicians = (count) => {
  const technicians = [];
  for (let i = 0; i < count; i++) {
    const name = getRandomItem(names);
    const location = getRandomItem(cities);
    const category = getRandomItem(Object.keys(skills));
    const technician = {
      name: `${name} ${getRandomItem(names)}`,
      email: `${name.toLowerCase()}.${i}@example.com`,
      password: 'password123',
      role: 'technician',
      location: {
        city: location.city,
        state: location.state,
      },
      phone: `9${Math.floor(100000000 + Math.random() * 900000000)}`,
      category: category,
      skills: getRandomItem(skills[category]),
      experience: Math.floor(Math.random() * 20) + 1,
      hourlyRate: Math.floor(Math.random() * 1000) + 500,
      bio: `Experienced ${category} from ${location.city}.`,
    };
    technicians.push(technician);
  }
  return technicians;
};

const generateRegularUsers = (count) => {
  const users = [];
  for (let i = 0; i < count; i++) {
    const name = getRandomItem(names);
    const user = {
      name: `${name} ${getRandomItem(names)}`,
      email: `user.${name.toLowerCase()}.${i}@example.com`,
      password: 'password123',
      role: 'user',
    };
    users.push(user);
  }
  return users;
};

const technicians = generateTechnicians(2500);
fs.writeFileSync(
  path.join(__dirname, '..', '_data', 'technicians_large.json'),
  JSON.stringify(technicians, null, 2)
);
console.log('Generated 2500 technicians.');

const regularUsers = generateRegularUsers(200);
fs.writeFileSync(
  path.join(__dirname, '..', '_data', 'users_regular.json'),
  JSON.stringify(regularUsers, null, 2)
);
console.log('Generated 200 regular users.');
